import { Helmet } from "react-helmet-async";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const DisclaimerPage = () => {
  const lastUpdated = "January 1, 2024";

  return (
    <>
      <Helmet>
        <title>Disclaimer - AIWriterPros</title>
        <meta name="description" content="Read AIWriterPros' disclaimer to understand the limitations and responsibilities regarding AI-generated content and our services." />
        <link rel="canonical" href="https://aiwriterpros.lovable.app/disclaimer" />
        <meta name="robots" content="noindex, follow" />
      </Helmet>
      <div className="min-h-screen">
        <Header />

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-4">Disclaimer</h1>
          <p className="text-muted-foreground mb-8">Last Updated: {lastUpdated}</p>

          <div className="prose prose-lg max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-bold mb-4">General Disclaimer</h2>
              <p className="text-muted-foreground">
                The information provided by AIWriterPros ("we," "us," or "our") on our website and through our services
                is for general informational purposes only. All information is provided in good faith, however we make no
                representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity,
                reliability, availability, or completeness of any information.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">AI-Generated Content Disclaimer</h2>
              <p className="text-muted-foreground">
                Content generated by our AI tools is created using machine learning algorithms and may not always be accurate,
                complete, or appropriate for your specific needs. Users are solely responsible for:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground mt-4">
                <li>Reviewing and fact-checking all AI-generated content</li>
                <li>Editing content for accuracy, tone, and appropriateness</li>
                <li>Ensuring content complies with applicable laws and regulations</li>
                <li>Verifying product information and specifications</li>
                <li>Confirming any claims, statistics, or recommendations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">SEO Results Disclaimer</h2>
              <p className="text-muted-foreground">
                While our tools are designed to create SEO-optimized content, we do not guarantee specific search engine
                rankings or results. SEO success depends on many factors including but not limited to: content quality,
                website authority, competition, algorithm changes, and implementation. Past performance does not guarantee
                future results.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Amazon Affiliate Disclaimer</h2>
              <p className="text-muted-foreground">
                AIWriterPros is a participant in the Amazon Services LLC Associates Program, an affiliate advertising program
                designed to provide a means for sites to earn advertising fees by advertising and linking to Amazon.com.
                Product prices and availability may change without notice. We are not responsible for pricing errors or
                product availability on third-party websites.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Product Information Accuracy</h2>
              <p className="text-muted-foreground">
                Information about products extracted from Amazon and other sources may not reflect the most current product
                details, specifications, or availability. Always verify product information directly with the manufacturer
                or retailer before making purchasing decisions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Third-Party Links</h2>
              <p className="text-muted-foreground">
                Our services may contain links to third-party websites or services that are not owned or controlled by
                AIWriterPros. We have no control over, and assume no responsibility for, the content, privacy policies,
                or practices of any third-party websites or services. You acknowledge and agree that we shall not be
                responsible or liable for any damage or loss caused by use of such content or services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Professional Advice Disclaimer</h2>
              <p className="text-muted-foreground">
                The content generated by our services is not intended to be a substitute for professional advice. Always
                seek the advice of qualified professionals regarding specific questions or concerns. Never disregard
                professional advice or delay seeking it because of something you have read in AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Service Availability</h2>
              <p className="text-muted-foreground">
                We strive to provide uninterrupted service but cannot guarantee 100% uptime. Our services may be temporarily
                unavailable for maintenance, updates, or due to circumstances beyond our control. We are not liable for any
                loss or damage resulting from service interruptions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Changes to Services</h2>
              <p className="text-muted-foreground">
                We reserve the right to modify, suspend, or discontinue any aspect of our services at any time without prior
                notice. We are not liable to you or any third party for any modification, suspension, or discontinuance of
                our services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2>
              <p className="text-muted-foreground">
                Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a
                result of the use of our services or reliance on any information provided. Your use of our services and
                your reliance on any information is solely at your own risk.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Contact Information</h2>
              <p className="text-muted-foreground">
                If you have questions about this disclaimer, please contact us at:<br />
                Email: legal@aiwriterpros.com<br />
                Address: 123 Innovation Drive, San Francisco, CA 94105
              </p>
            </section>
          </div>
        </div>
      </div>

        <Footer />
      </div>
    </>
  );
};

export default DisclaimerPage;
